drop extension if exists "pg_net";


  create table "public"."buyer_profiles" (
    "id" uuid not null,
    "family_size" smallint,
    "budget" numeric,
    "preferred_num_bedrooms" smallint,
    "preferred_property_types" text[],
    "preferred_locations" text[]
      );


alter table "public"."buyer_profiles" enable row level security;


  create table "public"."estate_agencies" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "logo_url" text
      );


alter table "public"."estate_agencies" enable row level security;


  create table "public"."estate_agency_location" (
    "location_id" uuid not null default gen_random_uuid(),
    "estate_agency_id" uuid,
    "phone_number" text,
    "email_address" text,
    "address_line_1" text,
    "address_line_2" text,
    "city" text,
    "post_code" text
      );


alter table "public"."estate_agency_location" enable row level security;


  create table "public"."estate_agent_profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "estate_agency_id" uuid
      );


alter table "public"."estate_agent_profiles" enable row level security;


  create table "public"."properties" (
    "id" bigint generated by default as identity not null,
    "added_at" timestamp with time zone not null default now(),
    "title" text not null,
    "price" numeric not null,
    "description" text not null,
    "agency_id" uuid not null,
    "seller_id" uuid,
    "address_line_1" text not null,
    "address_line_2" text,
    "city" text not null,
    "post_code" text not null,
    "num_bedrooms" smallint,
    "num_bathrooms" smallint,
    "property_type" text,
    "square_feet" numeric,
    "council_tax_band" text,
    "epc_rating" text,
    "tenure_type" text,
    "media_url" text,
    "home_report_url" text,
    "schedule_url" text,
    "maps_url" text,
    "price_type" text
      );


alter table "public"."properties" enable row level security;


  create table "public"."user_roles" (
    "user_id" uuid not null,
    "granted_at" timestamp with time zone not null default now(),
    "role" text default 'NULL'::text,
    "granted_by" uuid not null
      );


alter table "public"."user_roles" enable row level security;


  create table "public"."users" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "user_goals" text[] default '{}'::text[],
    "onboarded" boolean default false,
    "email" text
      );


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX buyers_id_key ON public.buyer_profiles USING btree (id);

CREATE UNIQUE INDEX buyers_pkey ON public.buyer_profiles USING btree (id);

CREATE UNIQUE INDEX estate_agencies_pkey ON public.estate_agencies USING btree (id);

CREATE UNIQUE INDEX estate_agency_location_pkey ON public.estate_agency_location USING btree (location_id);

CREATE UNIQUE INDEX estate_agent_profiles_pkey ON public.estate_agent_profiles USING btree (id);

CREATE UNIQUE INDEX properties_pkey ON public.properties USING btree (id);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (user_id);

CREATE UNIQUE INDEX users_email_address_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_id_key ON public.users USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."buyer_profiles" add constraint "buyers_pkey" PRIMARY KEY using index "buyers_pkey";

alter table "public"."estate_agencies" add constraint "estate_agencies_pkey" PRIMARY KEY using index "estate_agencies_pkey";

alter table "public"."estate_agency_location" add constraint "estate_agency_location_pkey" PRIMARY KEY using index "estate_agency_location_pkey";

alter table "public"."estate_agent_profiles" add constraint "estate_agent_profiles_pkey" PRIMARY KEY using index "estate_agent_profiles_pkey";

alter table "public"."properties" add constraint "properties_pkey" PRIMARY KEY using index "properties_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."buyer_profiles" add constraint "buyers_budget_check" CHECK ((budget > (0)::numeric)) not valid;

alter table "public"."buyer_profiles" validate constraint "buyers_budget_check";

alter table "public"."buyer_profiles" add constraint "buyers_id_fkey" FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."buyer_profiles" validate constraint "buyers_id_fkey";

alter table "public"."buyer_profiles" add constraint "buyers_id_key" UNIQUE using index "buyers_id_key";

alter table "public"."estate_agency_location" add constraint "estate_agency_location_estate_agency_id_fkey" FOREIGN KEY (estate_agency_id) REFERENCES public.estate_agencies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."estate_agency_location" validate constraint "estate_agency_location_estate_agency_id_fkey";

alter table "public"."estate_agent_profiles" add constraint "estate_agent_profiles_estate_agency_id_fkey" FOREIGN KEY (estate_agency_id) REFERENCES public.estate_agencies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."estate_agent_profiles" validate constraint "estate_agent_profiles_estate_agency_id_fkey";

alter table "public"."estate_agent_profiles" add constraint "estate_agent_profiles_id_fkey" FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."estate_agent_profiles" validate constraint "estate_agent_profiles_id_fkey";

alter table "public"."properties" add constraint "properties_agency_id_fkey" FOREIGN KEY (agency_id) REFERENCES public.estate_agencies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."properties" validate constraint "properties_agency_id_fkey";

alter table "public"."properties" add constraint "properties_council_tax_band_check" CHECK ((length(council_tax_band) <= 1)) not valid;

alter table "public"."properties" validate constraint "properties_council_tax_band_check";

alter table "public"."properties" add constraint "properties_epc_rating_check" CHECK ((length(epc_rating) <= 1)) not valid;

alter table "public"."properties" validate constraint "properties_epc_rating_check";

alter table "public"."properties" add constraint "properties_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES public.user_roles(user_id) not valid;

alter table "public"."properties" validate constraint "properties_seller_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey";

alter table "public"."users" add constraint "users_email_address_key" UNIQUE using index "users_email_address_key";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_id_fkey";

alter table "public"."users" add constraint "users_id_key" UNIQUE using index "users_id_key";

alter table "public"."users" add constraint "users_onboarded_check" CHECK ((onboarded = ANY (ARRAY[true, false]))) not valid;

alter table "public"."users" validate constraint "users_onboarded_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_users_granted_by_agent()
 RETURNS TABLE(id uuid, first_name text, last_name text, email text)
 LANGUAGE plpgsql
AS $function$ 
begin
return query
  select distinct u.id, u.first_name, u.last_name, u.email
  from users u
  inner join user_roles ur on u.id = ur.user_id
  where ur.granted_by = auth.uid();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.users (id, email)
  values (new.id, new.email);

  if new.raw_user_meta_data ? 'role' then
  insert into public.user_roles(user_id, role, granted_by)
  values (new.id, new.raw_user_meta_data->>'role', (new.raw_user_meta_data->>'granted_by')::uuid);

  if new.raw_user_meta_data->>'role' = 'agent' then
  insert into public.estate_agent_profiles(id, estate_agency_id)
  values (new.id, (new.raw_user_meta_data->>'agency_id')::uuid);
  end if;
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid() and ur.role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_current_user_agent()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid() and ur.role = 'agent'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_user_admin(p_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = p_id and ur.role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_user_estate_agent(p_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = p_id and ur.role = 'agent'
  );$function$
;

CREATE OR REPLACE FUNCTION public.update_buyer_profile(p_id uuid, p_budget numeric, p_family_size smallint, p_preferred_num_bedrooms smallint, p_preferred_property_types text[], p_preferred_locations text[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  update buyer_profiles
  set 
  family_size = p_family_size,
  budget = p_budget,
  preferred_num_bedrooms = p_preferred_num_bedrooms,
  preferred_property_types = p_preferred_property_types,
  preferred_locations = p_preferred_locations

  where buyer_profiles.id = id;

  update users
  set onboarded = true
  where users.id = id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upgrade_user_to_agent(p_user_id uuid, p_agency_id uuid, p_admin_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$ 
begin
  insert into user_roles (user_id, role, granted_by)
  values 
  (p_user_id, 'agent', p_admin_id);

  insert into estate_agent_profiles (id, estate_agency_id)
  values (p_user_id, p_agency_id);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upgrade_user_to_seller(p_user_id uuid, p_agent_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$begin
  insert into user_roles (user_id, role, granted_by)
  values 
  (p_user_id, 'seller', p_agent_id);
end;$function$
;

grant delete on table "public"."buyer_profiles" to "anon";

grant insert on table "public"."buyer_profiles" to "anon";

grant references on table "public"."buyer_profiles" to "anon";

grant select on table "public"."buyer_profiles" to "anon";

grant trigger on table "public"."buyer_profiles" to "anon";

grant truncate on table "public"."buyer_profiles" to "anon";

grant update on table "public"."buyer_profiles" to "anon";

grant delete on table "public"."buyer_profiles" to "authenticated";

grant insert on table "public"."buyer_profiles" to "authenticated";

grant references on table "public"."buyer_profiles" to "authenticated";

grant select on table "public"."buyer_profiles" to "authenticated";

grant trigger on table "public"."buyer_profiles" to "authenticated";

grant truncate on table "public"."buyer_profiles" to "authenticated";

grant update on table "public"."buyer_profiles" to "authenticated";

grant delete on table "public"."buyer_profiles" to "service_role";

grant insert on table "public"."buyer_profiles" to "service_role";

grant references on table "public"."buyer_profiles" to "service_role";

grant select on table "public"."buyer_profiles" to "service_role";

grant trigger on table "public"."buyer_profiles" to "service_role";

grant truncate on table "public"."buyer_profiles" to "service_role";

grant update on table "public"."buyer_profiles" to "service_role";

grant delete on table "public"."estate_agencies" to "anon";

grant insert on table "public"."estate_agencies" to "anon";

grant references on table "public"."estate_agencies" to "anon";

grant select on table "public"."estate_agencies" to "anon";

grant trigger on table "public"."estate_agencies" to "anon";

grant truncate on table "public"."estate_agencies" to "anon";

grant update on table "public"."estate_agencies" to "anon";

grant delete on table "public"."estate_agencies" to "authenticated";

grant insert on table "public"."estate_agencies" to "authenticated";

grant references on table "public"."estate_agencies" to "authenticated";

grant select on table "public"."estate_agencies" to "authenticated";

grant trigger on table "public"."estate_agencies" to "authenticated";

grant truncate on table "public"."estate_agencies" to "authenticated";

grant update on table "public"."estate_agencies" to "authenticated";

grant delete on table "public"."estate_agencies" to "service_role";

grant insert on table "public"."estate_agencies" to "service_role";

grant references on table "public"."estate_agencies" to "service_role";

grant select on table "public"."estate_agencies" to "service_role";

grant trigger on table "public"."estate_agencies" to "service_role";

grant truncate on table "public"."estate_agencies" to "service_role";

grant update on table "public"."estate_agencies" to "service_role";

grant delete on table "public"."estate_agency_location" to "anon";

grant insert on table "public"."estate_agency_location" to "anon";

grant references on table "public"."estate_agency_location" to "anon";

grant select on table "public"."estate_agency_location" to "anon";

grant trigger on table "public"."estate_agency_location" to "anon";

grant truncate on table "public"."estate_agency_location" to "anon";

grant update on table "public"."estate_agency_location" to "anon";

grant delete on table "public"."estate_agency_location" to "authenticated";

grant insert on table "public"."estate_agency_location" to "authenticated";

grant references on table "public"."estate_agency_location" to "authenticated";

grant select on table "public"."estate_agency_location" to "authenticated";

grant trigger on table "public"."estate_agency_location" to "authenticated";

grant truncate on table "public"."estate_agency_location" to "authenticated";

grant update on table "public"."estate_agency_location" to "authenticated";

grant delete on table "public"."estate_agency_location" to "service_role";

grant insert on table "public"."estate_agency_location" to "service_role";

grant references on table "public"."estate_agency_location" to "service_role";

grant select on table "public"."estate_agency_location" to "service_role";

grant trigger on table "public"."estate_agency_location" to "service_role";

grant truncate on table "public"."estate_agency_location" to "service_role";

grant update on table "public"."estate_agency_location" to "service_role";

grant delete on table "public"."estate_agent_profiles" to "anon";

grant insert on table "public"."estate_agent_profiles" to "anon";

grant references on table "public"."estate_agent_profiles" to "anon";

grant select on table "public"."estate_agent_profiles" to "anon";

grant trigger on table "public"."estate_agent_profiles" to "anon";

grant truncate on table "public"."estate_agent_profiles" to "anon";

grant update on table "public"."estate_agent_profiles" to "anon";

grant delete on table "public"."estate_agent_profiles" to "authenticated";

grant insert on table "public"."estate_agent_profiles" to "authenticated";

grant references on table "public"."estate_agent_profiles" to "authenticated";

grant select on table "public"."estate_agent_profiles" to "authenticated";

grant trigger on table "public"."estate_agent_profiles" to "authenticated";

grant truncate on table "public"."estate_agent_profiles" to "authenticated";

grant update on table "public"."estate_agent_profiles" to "authenticated";

grant delete on table "public"."estate_agent_profiles" to "service_role";

grant insert on table "public"."estate_agent_profiles" to "service_role";

grant references on table "public"."estate_agent_profiles" to "service_role";

grant select on table "public"."estate_agent_profiles" to "service_role";

grant trigger on table "public"."estate_agent_profiles" to "service_role";

grant truncate on table "public"."estate_agent_profiles" to "service_role";

grant update on table "public"."estate_agent_profiles" to "service_role";

grant delete on table "public"."properties" to "anon";

grant insert on table "public"."properties" to "anon";

grant references on table "public"."properties" to "anon";

grant select on table "public"."properties" to "anon";

grant trigger on table "public"."properties" to "anon";

grant truncate on table "public"."properties" to "anon";

grant update on table "public"."properties" to "anon";

grant delete on table "public"."properties" to "authenticated";

grant insert on table "public"."properties" to "authenticated";

grant references on table "public"."properties" to "authenticated";

grant select on table "public"."properties" to "authenticated";

grant trigger on table "public"."properties" to "authenticated";

grant truncate on table "public"."properties" to "authenticated";

grant update on table "public"."properties" to "authenticated";

grant delete on table "public"."properties" to "service_role";

grant insert on table "public"."properties" to "service_role";

grant references on table "public"."properties" to "service_role";

grant select on table "public"."properties" to "service_role";

grant trigger on table "public"."properties" to "service_role";

grant truncate on table "public"."properties" to "service_role";

grant update on table "public"."properties" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


  create policy "Enable insert for users based on user_id"
  on "public"."buyer_profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable update for users based on user_id"
  on "public"."buyer_profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable users to view their own data only"
  on "public"."buyer_profiles"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable read access for all users"
  on "public"."estate_agencies"
  as permissive
  for select
  to public
using (true);



  create policy "admins can create profiles"
  on "public"."estate_agent_profiles"
  as permissive
  for select
  to public
using (public.is_current_user_admin());



  create policy "admins can do anything"
  on "public"."estate_agent_profiles"
  as permissive
  for all
  to public
using (public.is_current_user_admin())
with check (public.is_current_user_admin());



  create policy "Enable users to view their own data only"
  on "public"."user_roles"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "admins can insert estate agents"
  on "public"."user_roles"
  as permissive
  for insert
  to public
with check ((public.is_current_user_admin() AND (role = 'agent'::text)));



  create policy "admins can select all data"
  on "public"."user_roles"
  as permissive
  for select
  to public
using (public.is_current_user_admin());



  create policy "agents can insert sellers"
  on "public"."user_roles"
  as permissive
  for insert
  to public
with check ((public.is_current_user_agent() AND (role = 'seller'::text)));



  create policy "agents can select sellers they added"
  on "public"."user_roles"
  as permissive
  for select
  to public
using ((public.is_current_user_agent() AND (role = 'seller'::text) AND (granted_by = auth.uid())));



  create policy "Enable insert for users based on user_id"
  on "public"."users"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable update for users based on user_id"
  on "public"."users"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable users to view their own data only"
  on "public"."users"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = id));



  create policy "admins can select all data"
  on "public"."users"
  as permissive
  for select
  to public
using (public.is_current_user_admin());



  create policy "agents can select users they added"
  on "public"."users"
  as permissive
  for select
  to authenticated
using (public.is_current_user_agent());


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


