
  create table "public"."property_tags" (
    "property_id" bigint generated by default as identity not null,
    "tag_id" bigint not null,
    "user_id" uuid,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."property_tags" enable row level security;


  create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "is_seed" boolean not null default true
      );


alter table "public"."tags" enable row level security;

alter table "public"."properties" add column "driveway" boolean default false;

alter table "public"."properties" add column "garden" boolean default false;

CREATE UNIQUE INDEX property_tags_pkey ON public.property_tags USING btree (property_id, tag_id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."property_tags" add constraint "property_tags_pkey" PRIMARY KEY using index "property_tags_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."property_tags" add constraint "property_tags_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."property_tags" validate constraint "property_tags_property_id_fkey";

alter table "public"."property_tags" add constraint "property_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."property_tags" validate constraint "property_tags_tag_id_fkey";

alter table "public"."property_tags" add constraint "property_tags_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL not valid;

alter table "public"."property_tags" validate constraint "property_tags_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.users (id, email)
  values (new.id, new.email);

  if new.raw_user_meta_data ? 'role' then
  insert into public.user_roles(user_id, role, granted_by)
  values (new.id, new.raw_user_meta_data->>'role', (new.raw_user_meta_data->>'granted_by')::uuid);

  if new.raw_user_meta_data->>'role' = 'agent' then
  insert into public.estate_agent_profiles(id, estate_agency_location_id)
  values (new.id, (new.raw_user_meta_data->>'location_id')::uuid);
  end if;
  end if;
  return new;
end;
$function$
;

grant delete on table "public"."property_tags" to "anon";

grant insert on table "public"."property_tags" to "anon";

grant references on table "public"."property_tags" to "anon";

grant select on table "public"."property_tags" to "anon";

grant trigger on table "public"."property_tags" to "anon";

grant truncate on table "public"."property_tags" to "anon";

grant update on table "public"."property_tags" to "anon";

grant delete on table "public"."property_tags" to "authenticated";

grant insert on table "public"."property_tags" to "authenticated";

grant references on table "public"."property_tags" to "authenticated";

grant select on table "public"."property_tags" to "authenticated";

grant trigger on table "public"."property_tags" to "authenticated";

grant truncate on table "public"."property_tags" to "authenticated";

grant update on table "public"."property_tags" to "authenticated";

grant delete on table "public"."property_tags" to "service_role";

grant insert on table "public"."property_tags" to "service_role";

grant references on table "public"."property_tags" to "service_role";

grant select on table "public"."property_tags" to "service_role";

grant trigger on table "public"."property_tags" to "service_role";

grant truncate on table "public"."property_tags" to "service_role";

grant update on table "public"."property_tags" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."property_tags"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."property_tags"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."tags"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."tags"
  as permissive
  for select
  to public
using (true);



