drop policy "agents can select sellers they added" on "public"."user_roles";


  create table "public"."property_seller_info" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "seller_description" text
      );


alter table "public"."property_seller_info" enable row level security;

alter table "public"."properties" drop column "floorplan_url";

CREATE UNIQUE INDEX property_seller_info_pkey ON public.property_seller_info USING btree (id);

alter table "public"."property_seller_info" add constraint "property_seller_info_pkey" PRIMARY KEY using index "property_seller_info_pkey";

alter table "public"."property_seller_info" add constraint "property_seller_info_id_fkey" FOREIGN KEY (id) REFERENCES public.properties(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."property_seller_info" validate constraint "property_seller_info_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.does_property_belong_to_seller(p_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
begin
return exists (

  select 1 

  from properties p

  where p_id = p.id and p.seller_id = auth.uid() 

  limit 1
);
end;
$function$
;

grant delete on table "public"."property_seller_info" to "anon";

grant insert on table "public"."property_seller_info" to "anon";

grant references on table "public"."property_seller_info" to "anon";

grant select on table "public"."property_seller_info" to "anon";

grant trigger on table "public"."property_seller_info" to "anon";

grant truncate on table "public"."property_seller_info" to "anon";

grant update on table "public"."property_seller_info" to "anon";

grant delete on table "public"."property_seller_info" to "authenticated";

grant insert on table "public"."property_seller_info" to "authenticated";

grant references on table "public"."property_seller_info" to "authenticated";

grant select on table "public"."property_seller_info" to "authenticated";

grant trigger on table "public"."property_seller_info" to "authenticated";

grant truncate on table "public"."property_seller_info" to "authenticated";

grant update on table "public"."property_seller_info" to "authenticated";

grant delete on table "public"."property_seller_info" to "service_role";

grant insert on table "public"."property_seller_info" to "service_role";

grant references on table "public"."property_seller_info" to "service_role";

grant select on table "public"."property_seller_info" to "service_role";

grant trigger on table "public"."property_seller_info" to "service_role";

grant truncate on table "public"."property_seller_info" to "service_role";

grant update on table "public"."property_seller_info" to "service_role";


  create policy "Enable read access for all users"
  on "public"."property_seller_info"
  as permissive
  for select
  to public
using (true);



  create policy "Sellers can edit and add to their own properties"
  on "public"."property_seller_info"
  as permissive
  for all
  to authenticated
using (public.does_property_belong_to_seller(id))
with check (true);



  create policy "agents can select all sellers"
  on "public"."user_roles"
  as permissive
  for select
  to public
using ((public.is_current_user_agent() AND (role = 'seller'::text)));



